# ============================================================================
# Render Blueprint - Instagram Automation Dashboard
# ============================================================================
# 
# VERIFIED CONFIGURATION - Based on actual repository structure
# Last Updated: January 7, 2025
# Repository: instagram-automation-dashboard (Post-Cleanup)
#
# IMPORTANT: This configuration matches your actual folder structure:
# - Frontend: Root directory (package.json, src/, vite.config.ts)
# - Backend: ./backend.api (note the DOT, not underscore)
# ============================================================================

services:
  # ==========================================================================
  # SERVICE 1: FRONTEND - React/Vite Static Site
  # ==========================================================================
  - type: web
    name: instagram-dashboard-frontend
    runtime: static
    env: static
    
    # Build Configuration
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    
    # Root directory - Frontend is at project root
    rootDir: .
    
    # Health Check (for static sites, Render checks if files exist)
    
    # SPA Routing - All routes redirect to index.html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    
    # Environment Variables for Frontend
    envVars:
      - key: NODE_ENV
        value: production
      
      # CRITICAL: Update this after backend deployment
      - key: VITE_API_URL
        value: https://instagram-dashboard-backend.onrender.com
      
      - key: VITE_APP_NAME
        value: Instagram Automation Dashboard
      
      # Supabase Direct Connection (No tunnel in production)
      - key: VITE_SUPABASE_URL
        sync: false  # Set in Render dashboard
      
      - key: VITE_SUPABASE_ANON_KEY
        sync: false  # Set in Render dashboard
      
      # Optional: Analytics
      - key: VITE_ENABLE_ANALYTICS
        value: "true"
    
    # Auto-deploy Settings
    autoDeploy: true
    branch: main
    
    # Build Settings
    buildFilter:
      paths:
        - src/**
        - public/**
        - index.html
        - vite.config.ts
        - package.json
        - package-lock.json

  # ==========================================================================
  # SERVICE 2: BACKEND - Express.js API Server
  # ==========================================================================
  - type: web
    name: instagram-dashboard-backend
    runtime: node
    env: node
    
    # CRITICAL FIX: Correct path to backend folder (with DOT not underscore)
    rootDir: ./backend.api
    
    # Build & Start Commands
    buildCommand: npm install
    startCommand: npm start
    
    # Server Configuration
    plan: starter  # $7/month - Upgrade from free for better performance
    region: oregon  # Choose region closest to your users
    
    # Health Check Configuration
    healthCheckPath: /health
    
    # Environment Variables for Backend
    envVars:
      # Node Environment
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: "3001"
      
      # ================================================================
      # SUPABASE CONFIGURATION - Direct Connection Only
      # ================================================================
      - key: SUPABASE_URL
        sync: false  # Set manually in Render dashboard
        # Example: https://uromexjprcrjfmhkmgxa.supabase.co
      
      - key: SUPABASE_SERVICE_KEY
        sync: false  # CRITICAL: Never commit this to git!
      
      - key: SUPABASE_ANON_KEY
        sync: false  # Set manually in Render dashboard
      
      # Disable tunnel for production
      - key: USE_DB_TUNNEL
        value: "false"
      
      # ================================================================
      # CLOUDFLARE TUNNEL - API Only
      # ================================================================
      - key: CLOUDFLARE_TUNNEL_TOKEN
        sync: false  # Set manually in Render dashboard
      
      # ================================================================
      # META/INSTAGRAM API CREDENTIALS
      # ================================================================
      - key: META_APP_ID
        sync: false
      
      - key: META_APP_SECRET
        sync: false
      
      - key: META_ACCESS_TOKEN
        sync: false
      
      - key: INSTAGRAM_CLIENT_ID
        sync: false
      
      - key: INSTAGRAM_CLIENT_SECRET
        sync: false
      
      # ================================================================
      # WEBHOOK CONFIGURATION
      # ================================================================
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
        # Recommended: instagram_automation_secure_token_2025
      
      - key: VITE_WEBHOOK_URL
        value: https://instagram-dashboard-backend.onrender.com
      
      # ================================================================
      # SECURITY & ENCRYPTION
      # ================================================================
      - key: JWT_SECRET
        sync: false  # Generate a strong secret
      
      - key: ENCRYPTION_KEY
        sync: false  # 64-character hex string
      
      # ================================================================
      # CORS CONFIGURATION
      # ================================================================
      - key: CORS_ORIGIN
        value: https://instagram-dashboard-frontend.onrender.com
      
      # ================================================================
      # N8N INTEGRATION (Optional)
      # ================================================================
      - key: N8N_WEBHOOK_BASE
        sync: false  # Your N8N instance URL
      
      - key: N8N_DM_WEBHOOK
        sync: false
      
      - key: N8N_COMMENT_WEBHOOK
        sync: false
      
      # ================================================================
      # OPERATIONAL SETTINGS
      # ================================================================
      - key: LOG_LEVEL
        value: info
      
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"  # 15 minutes
      
      # Static IP (if using Fixie or similar service)
      - key: BACKEND_STATIC_IP
        sync: false  # Your static IP for Supabase whitelist
    
    # Auto-deploy Settings
    autoDeploy: true
    branch: main
    
    # Build Settings - Only rebuild when backend changes
    buildFilter:
      paths:
        - backend.api/**